services:
  4cg:
    build: .
    ports:
      - 8050:8080
    volumes:
      - ./data/apache/4cg:/opt/4cg
      # - /mnt/md2/incoming/pocket/Latif/boards.4chan.org:/var/www/html/4chan-boards
      # - /opt/git/4chan-downloader/downloads:/opt/4chan-downloads
      # - /mnt/md2/incoming/pocket/Latif/rule34video:/opt/4chan-downloads
      - /mnt/md2/incoming/pocket:/opt/4cg/4chan-boards
    restart: unless-stopped
